import type { Client, Task, Invoice, Service } from '@/types';

const commonServices: Service[] = [
  { id: 's1', name: 'Gestión de Redes Sociales', price: 500 },
  { id: 's2', name: 'Optimización SEO', price: 750 },
  { id: 's3', name: 'Creación de Contenido (Blog)', price: 300 },
  { id: 's4', name: 'Gestión de Campañas PPC', price: 600 },
];

export const mockClients: Client[] = [
  {
    id: 'c1',
    name: 'Innovatech Solutions',
    email: 'contact@innovatech.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    services: [commonServices[0], commonServices[1]],
    contractStartDate: '2023-01-15',
    nextBillingDate: '2024-07-15',
    profileSummary: 'Innovatech Solutions es una empresa tecnológica B2B especializada en analítica impulsada por IA. Público objetivo: CTOs, científicos de datos. Valores: Innovación, eficiencia, seguridad de datos. Tono: Profesional, vanguardista.',
    clinica: 'Sede Central Tech',
    telefono: '+1-202-555-01 Innovatech',
    serviciosActivosGeneral: 'Consultoría IA, Desarrollo de Software',
    pagado: true,
    notas: 'Cliente prioritario, alto potencial de crecimiento.',
    dominioWeb: 'innovatech.com',
    tipoServicioWeb: 'Hosting Premium Plus',
    vencimientoWeb: '2025-01-15',
    plataformasRedesSociales: 'LinkedIn, Twitter',
    detallesRedesSociales: 'LinkedIn: Enfoque en liderazgo de pensamiento. Twitter: Noticias y actualizaciones de la industria.',
    serviciosContratadosAdicionales: 'Soporte técnico extendido 24/7',
    configuracionRedesSociales: 'Acceso de administrador otorgado para todas las plataformas.',
    credencialesRedesUsuario: 'innovatech_admin',
    credencialesRedesContrasena: 'securePass123!',
  },
  {
    id: 'c2',
    name: 'GreenLeaf Organics',
    email: 'hello@greenleaf.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    services: [commonServices[0], commonServices[2]],
    contractStartDate: '2023-03-01',
    nextBillingDate: '2024-08-01',
    profileSummary: 'GreenLeaf Organics ofrece productos premium de cuidado de la piel orgánicos. Público objetivo: Consumidores conscientes de la salud, millennials, mujeres de 25-55 años. Valores: Ingredientes naturales, sostenibilidad, origen ético. Tono: Cálido, confiable, ecológico.',
    clinica: 'Tienda Principal GreenLeaf',
    telefono: '+1-303-555-01 GreenLeaf',
    serviciosActivosGeneral: 'Marketing de Contenidos, Email Marketing',
    pagado: true,
    notas: 'Campaña de influencers en curso.',
    dominioWeb: 'greenleaforganics.com',
    tipoServicioWeb: 'Plataforma eCommerce Shopify',
    vencimientoWeb: '2024-12-01',
    plataformasRedesSociales: 'Instagram, Facebook, Pinterest',
    detallesRedesSociales: 'Instagram: Alto contenido visual, historias diarias. Facebook: Comunidad y promociones. Pinterest: Inspiración y tutoriales.',
    serviciosContratadosAdicionales: 'Fotografía de producto mensual',
    configuracionRedesSociales: 'Buffer conectado para programación.',
    credencialesRedesUsuario: 'greenleaf_social',
    credencialesRedesContrasena: 'natureLover2024#',
  },
  {
    id: 'c3',
    name: 'Apex Fitness Gear',
    email: 'support@apexfitness.com',
    services: [commonServices[3]],
    contractStartDate: '2023-05-20',
    nextBillingDate: '2024-07-20',
    profileSummary: 'Apex Fitness Gear vende ropa y equipamiento deportivo de alto rendimiento. Público objetivo: Entusiastas del fitness, atletas, asistentes al gimnasio. Valores: Rendimiento, durabilidad, motivación. Tono: Energético, inspirador, audaz.',
    clinica: 'Gimnasio Apex HQ',
    telefono: '+1-404-555-01 ApexFit',
    serviciosActivosGeneral: 'Publicidad en Redes Sociales',
    pagado: false,
    notas: 'Pendiente de pago de la última factura. Recordatorio enviado.',
    dominioWeb: 'apexfitnessgear.com',
    tipoServicioWeb: 'Alojamiento Básico',
    vencimientoWeb: '2024-11-20',
    plataformasRedesSociales: 'Instagram, TikTok, YouTube',
    detallesRedesSociales: 'Instagram: Videos de entrenamiento. TikTok: Desafíos y tendencias. YouTube: Reseñas de productos y tutoriales largos.',
    serviciosContratadosAdicionales: 'Video marketing promocional trimestral',
    configuracionRedesSociales: 'Google Analytics vinculado.',
    credencialesRedesUsuario: 'apex_marketing',
    credencialesRedesContrasena: 'strongLifeCycle!',
  },
];

export const mockTasks: Task[] = [
  {
    id: 't1',
    name: 'Borrador calendario redes Q3 para Innovatech',
    assignedTo: 'Alicia Pérez',
    dueDate: '2024-07-10',
    status: 'En Progreso',
    priority: 'Alta',
    clientId: 'c1',
    clientName: 'Innovatech Solutions',
    description: 'Planificar contenido para LinkedIn y Twitter para el tercer trimestre.',
  },
  {
    id: 't2',
    name: 'Investigación de palabras clave GreenLeaf',
    assignedTo: 'Roberto Gómez',
    dueDate: '2024-07-15',
    status: 'Pendiente',
    priority: 'Media',
    clientId: 'c2',
    clientName: 'GreenLeaf Organics',
    description: 'Identificar keywords para la nueva línea de productos orgánicos.',
  },
  {
    id: 't3',
    name: 'Finalizar copys PPC Apex Fitness Venta Verano',
    assignedTo: 'Carolina López',
    dueDate: '2024-07-05',
    status: 'Completada',
    priority: 'Alta',
    clientId: 'c3',
    clientName: 'Apex Fitness Gear',
    description: 'Revisar y aprobar los anuncios para la campaña de verano.',
  },
  {
    id: 't4',
    name: 'Informe mensual rendimiento Innovatech',
    assignedTo: 'Alicia Pérez',
    dueDate: '2024-07-25',
    status: 'Pendiente',
    priority: 'Media',
    clientId: 'c1',
    clientName: 'Innovatech Solutions',
    description: 'Compilar métricas de redes sociales y SEO del último mes.',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv001',
    clientName: 'Innovatech Solutions',
    clientId: 'c1',
    amount: 1250,
    dueDate: '2024-07-15',
    issuedDate: '2024-07-01',
    status: 'No Pagada',
    items: [
      { id: 'item1', description: 'Gestión de Redes Sociales', quantity: 1, unitPrice: 500 },
      { id: 'item2', description: 'Optimización SEO', quantity: 1, unitPrice: 750 },
    ],
    notes: 'Servicios correspondientes al mes de Julio.',
  },
  {
    id: 'inv002',
    clientName: 'GreenLeaf Organics',
    clientId: 'c2',
    amount: 800,
    dueDate: '2024-06-20',
    issuedDate: '2024-06-05',
    status: 'Pagada',
    items: [
      { id: 'item3', description: 'Gestión de Redes Sociales', quantity: 1, unitPrice: 500 },
      { id: 'item4', description: 'Creación de Contenido (Blog)', quantity: 1, unitPrice: 300 },
    ],
    notes: 'Pago recibido el 2024-06-18. Gracias!',
  },
  {
    id: 'inv003',
    clientName: 'Apex Fitness Gear',
    clientId: 'c3',
    amount: 600,
    dueDate: '2024-05-25',
    issuedDate: '2024-05-10',
    status: 'Vencida',
    items: [{ id: 'item5', description: 'Gestión de Campañas PPC', quantity: 1, unitPrice: 600 }],
    notes: 'Factura vencida. Por favor, procesar el pago urgentemente.',
  },
];
